### ISSUE TITLE
Invite kjbekkelund to be a collaborator

### ISSUE THREAD

**Issue by jlongster** [jlongster/redux-simple-router#101]
Hey @kjbekkelund, you've done a fantastic job not only writing code and researching a lot of ideas but also responding to other people's issues and PRs. It'd be great to give you commit access here so you can move things forward as you see fit. Of course I'll still be around too but feel free to merge stuff if you think it's ready.

**Comment by kjbekkelund** [comment]
Awesome! Thanks, @jlongster :sparkles:

**Comment by kjbekkelund** [comment]
@jlongster Btw, have you pushed all commits to master? `package.json` says 0.0.10

**Comment by jlongster** [comment]
Cool! Although I'd really rather avoid cherry-picking because the history diverges. Not a big deal this time but I'd rather merge. Welcome!

**Comment by ellbee** [comment]
:+1: Good call, @kjbekkelund has been a machine! :smile:
