### ISSUE TITLE
IndexRedirect causes infinite route

### ISSUE THREAD

**Issue by hunterc** [jlongster/redux-simple-router#102]
If I use an `IndexRedirect` with a basename I seem to get an infinite route.
Filing it here because it only happens when I call `syncReduxAndRouter`.

Commenting out the basename seems to resolve the issue ( I assume because there is nothing to repeat).

If I hit `/test`, I get a infinite loop of `/test/test/test/......` until the call stack is exceeded.

[Gist I'm using to verify](https://gist.github.com/hunterc/7c8896f7ff05f1928eb5)

**Comment by kjbekkelund** [comment]
We'll keep working on this in #103
