### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by mhahn** [jlongster/redux-simple-router#111]
Let me know if this isn't the right place for this issue.

I followed the structure you recommended for server side rendering, ie. if the component has a `fetchData` static method, which is called in a custom `createElement` function that gets passed to `Router`. One issue I'm running into is that the `fetchData` call will be executed before react life cycle methods.

Specifically, I have a search component that clears its cache within `componentWillUnmount`, lets call it component A. There is a scenario where we load another component (component B) which fetches search results in its `fetchData`.

what is happening now is:

as we transition from A to B:

- B's `fetchData` is called
- A's `componentWillUnmount` is called
- B's `componentWillMount` is called

this is breaking for me because `fetchData` thinks it has cached search results, which get cleared in `componentWillUnmount`.

If i fetch the results in component B's `componentWillMount` i'm triggering multiple search requests on the server side. It isn't a huge deal since only 1 hits the API since the subsequent one in componentWillMount uses the cache, but it is a little messy.

**Comment by kjbekkelund** [comment]
Is this related to redux-simple-router?

**Comment by mhahn** [comment]
It's related to: https://github.com/jlongster/redux-simple-router/issues/13, i guess that is a better place for it.

**Comment by kjbekkelund** [comment]
Ah, I see. I haven't read through that thread yet. But yeah, try to ask there and see :)
