### ISSUE TITLE
routing.path isn't deterministic (leading slash /)

### ISSUE THREAD

**Issue by rayshan** [jlongster/redux-simple-router#114]
Hello,

I have a route, `:title`. When the route is triggered:
- Via `react-router`'s `<Link to="title" />`, `state.routing.path` is `title`
- Loading the url, e.g. `localhost:4000/title`, directly, `state.routing.path` is `/title`

Is there a way to generate the same `state.routing.path`, or do we have to check for `/` everywhere?

**Comment by kjbekkelund** [comment]
Hi @rayshan. We rely on the result from `history.listen` to set the path: https://github.com/jlongster/redux-simple-router/blob/master/src/index.js#L103-L105

I don't have the same problem in my app, but I'm using hash history. Could you create a small reproducible example that shows this?

**Comment by rayshan** [comment]
Thanks for the quick reply. I think I found the problem: https://github.com/rackt/react-router/issues/2172

If I do `<Link to="title" />`, seems like 2 routes are hit, `/title` then `title`. This can be seen by using the browser back button - you have to click it twice to go back to `/`.

The problem is fixed by doing `<Link to="/title" />`. Now `state.routing.path` is always `/title`, and 1 click of back button gets back to `/`.

**Comment by kjbekkelund** [comment]
Thanks for the info :+1:
