### ISSUE TITLE
replacePath not working 

### ISSUE THREAD

**Issue by pkumar84** [jlongster/redux-simple-router#115]
Dear Developers, 

i am trying to replace url states to null so that back and forward navigation shouldn't work. 

For e.g. i have tabs , 
when user clicks on tab1 - pushState('tab/1'); works fine and update the url 
when user clicks on tab1 - pushState('tab/2'); works fine and update the url 
Until now Back and forward navigation works like charm . 

when user close tab1 i replace the state 
replaceState('tab/1', null, { avoidRouterUpdate: true });
ideally this should remove tab/1 stop behaving on back and forward navigation . 

since the tab1 has been deleted and and i had replacePath but as soon as i click on browser back navigation , it popups again[ that my code does based on the state received from this.props.params]  . 

is this expected behaviour or its bug around the system ?

**Comment by kjbekkelund** [comment]
Not sure I understand, but when you `avoidRouterUpdate` is doesn't touch the history at all. So perhaps try without it?

**Comment by pkumar84** [comment]
My bad, let me try to explain

i have Tabs when user clicks on each tab and once user do that i call pushPath and update URL , for e.g 

When user clicks on 
Tab1 - pushState('tab/1'); -url changed 
Tab2 - pushState('tab/2'); - url changed 

Now if i go back using back n forward navigation , i get correct state of url(using this.props.params)  and switch focus back to respective tab by looking at this.props.params.id 

now i have scenario where user can close individual tab or all tabs.  once user does that closed tab/tabs should never appear again , so technically i don't want history of that tab now that i have pushed using pushPath

to achieve this i am using replacePath() using  { avoidRouterUpdate: true } and  { avoidRouterUpdate: false } but seems like its not working. 

Am i using right API ? or its a bug ?

**Comment by kjbekkelund** [comment]
Could you create a reproducible example? `replacePath` works correctly in my app — I just double-checked.

Btw, avoid setting `avoidRouterUpdate` at all. You shouldn't need it to handle this.

**Comment by pkumar84** [comment]
sure, just to understand this API correct, 
replacePath will set existing path which has already been set using pushState and will remove all the path from history or only current path ?

**Comment by kjbekkelund** [comment]
If you `pushPath(foo)`, `pushPath(bar)` then `replacePath(baz)` will replace `bar` with `baz` in the URL, and going back in the browser will go to `foo`.

**Comment by pkumar84** [comment]
and if user come forward in the browser then bar will never appear, baz will appear, right ?
correct, that's how i intended to use this. i will create example this weekend. thank you .

**Comment by pkumar84** [comment]
what if i want to replace foo and bar with baz in one click e.g close all tabs ?

**Comment by kjbekkelund** [comment]
To learn more about what you can do with the browser history, check out https://developer.mozilla.org/en-US/docs/Web/API/History_API. You can also check out https://github.com/rackt/history, which is the library we use. If you have further questions, I suggest asking them on StackOverflow.

**Comment by pkumar84** [comment]
Thanks Kim, i understands now how replacePath works , thank you . and it works as per docs. it not bug, i was not well educated on replacePath, sorry again .
