### ISSUE TITLE
Resetting scroll positions during route change

### ISSUE THREAD

**Issue by azer** [jlongster/redux-simple-router#116]
When user navigates to another route by clicking a `Link`, scroll stays in same position when the page gets changed. It's a weird behavior, any way to fix it ?

**Comment by kjbekkelund** [comment]
We don't do anything related to scroll behaviour in this lib. We rely on [history](https://github.com/rackt/history) for everything related to navigation, so I think that's where you have to go look for details on scroll handling.

**Comment by halt-hammerzeit** [comment]
@azer Try using `scroll-behavior`
https://github.com/taion/scroll-behavior/issues/46#issuecomment-197891745
