### ISSUE TITLE
Changing route parameter

### ISSUE THREAD

**Issue by rzmz** [jlongster/redux-simple-router#125]
I have several routes like this:

Route name="routeName" path="/routeName/:deviceId" component={AnyComponent} 

How can I just change this :deviceId on any given route I am currently visiting?

Right now I am trying to do something like
let path = getState().routing.path.split('/');
And then changing the last element of the array and then using pushPath with joined new path string but something tells me this is not the correct way.

Sorry if this is a dumb question but I have been struggling with this one for quite some time now and I haven't found any help from the docs. Thanks.

**Comment by jlongster** [comment]
`pushPath` is the right way, but why are you not getting the param from react-router itself? All the params are available as a prop on routing components already.

**Comment by rzmz** [comment]
Thank you for your reply. I am new to react and redux and kept wondering why those props do not appear in my store. Closing this issue now.
