### ISSUE TITLE
Custom selector function for reducer state

### ISSUE THREAD

**Issue by idolize** [jlongster/redux-simple-router#16]
Right now [the docs say](https://github.com/jlongster/redux-simple-router#routereducer) that the reducer state `"must be named 'routing'"`.

I vote that we remove this requirement and let developers decide for themselves how they want to structure their app state. In fact, I currently use ImmutableJs `Map` objects for my state hierarchy (I wrote my own `combineReducers` function instead of the redux default), so I'm not even sure I can use this library as-is.

I [wrote a similar PR for `redux-router` here](https://github.com/rackt/redux-router/issues/15), which changes the API to accept a "selector" function instead of just assuming `getState().router`. We can likely do something similar here.

**Comment by jlongster** [comment]
Does #15 solve the problem? Looks like the custom function will get what you want. I hadn't even thought about other data structures, that's a great point.

**Comment by idolize** [comment]
That looks exactly how I had imagined it! Thanks @jlongster and @davezuko

**Comment by jlongster** [comment]
Will merge that once it's rebased!
