### ISSUE TITLE
Is it compatible with react-router <Link>?

### ISSUE THREAD

**Issue by moroshko** [jlongster/redux-simple-router#17]
When I do `dispatch(updatePath('/foo'))` all works great.
But, we have react-router `<Link>` components and they are broken now.
Can `redux-simple-router` work with react-router `<Link>`s, or we need to call `dispatch(updatePath(newPath))` for all those links now?

**Comment by jlongster** [comment]
`<Link>` should definitely work, I use it in my project. Links should trigger a react-router update, which fire's the `listen` hander on the history object which should update the redux state. Any chance you can try to find a small test case or put the code online?

**Comment by moroshko** [comment]
@jlongster Sorry, it was an issue in our app. Please ignore.
