### ISSUE TITLE
onEnter / onLeave functionality (access to state)?

### ISSUE THREAD

**Issue by alexbeletsky** [jlongster/redux-simple-router#20]
I had some frustration with [redux-router](https://github.com/rackt/redux-router/issues/172) both from configuration point of view and from impemenentation of something like `requireAuth()` function checks, that used in `onEnter()` hooks to prevent access to autorized only application parts. 

`redux-router` has an [issue](https://github.com/rackt/redux-router/issues/143) with that and I'm trying to understand, does it this also relate to `redux-simple-router` project.

Can state be accessed easily with this router?

**Comment by jlongster** [comment]
I don't think that issues applies to us at all, because we aren't doing anything with `onEnter`. That's 100% a react-router thing.

You are creating the store and the routes somewhere in a top-level file in your app, right? What you should probably do is install an `onEnter` hook into react-router that closes over the `store` that you've created, and you can simply call `store.getState`. Or you can use the `createElement` paramter of the `Router`; that's usually a better option than `onEnter`. It's totally up to you how to use react-router, but you should have a reference to `store` wherever you are doing that.

We definitely need a few example, and I will get to that soon.

**Comment by alexbeletsky** [comment]
Thanks for your comments,

Just for the record, this is the approach I really liked instead of using `onEnter` use `requiredAuth` component, [joshgeller/react-redux-jwt-auth-example/](https://github.com/joshgeller/react-redux-jwt-auth-example/blob/master/src/routes/index.js).

**Comment by dpwrussell** [comment]
@jlongster Did those examples get made?

Cheers

**Comment by jlongster** [comment]
We never made an official example is this usage, but several people in the community made many examples and one of them probably uses it: https://github.com/reactjs/react-router-redux#examples

**Comment by dpwrussell** [comment]
For reference, this is what I did.

Pass the `getState` function to the router component.
```jsx
export default class Root extends React.Component {
  render() {
    const { store, history } = this.props;
    const { getState } = store;
    return (

      <Provider store={ store }>
        <div>
          <RTRouter history={ history } getState={ getState }/>
          <DevTools />
        </div>
      </Provider>
    );
  }
}
```

User the `getState` function in the `requireAuth` method to read from redux state.
```jsx
export default class RTRouter extends React.Component {

  constructor() {
    super();

    this.requireAuth = this.requireAuth.bind(this);

    // Configure routes here as this solves a problem with hot loading where
    // the routes are recreated each time.
    this.routes = (
      <Route path='/' component={ ReagentTracker } >
        <IndexRoute component={ Home } />
        <Route path='about' component={ About } />
        <Route path='login' component={ Login } />
        <Route path='authzone' component={ SecretStuff } onEnter={ this.requireAuth } />
      </Route>
    );
  }

  requireAuth(nextState, replace) {
    const { getState } = this.props;

    // Use my reselect selector to determine if we are authenticated or not
    // Obviously this is not complete, but at this point it's easy to redirect or
    // initiate an action in order to login via cookie or whatever
    if (!isLoggedIn(getState())) {
      console.log("Not logged in");
    } else {
      console.log('We are already logged in');
    }
  }

  render() {
    const { history } = this.props;
    return (
      <Router history={ history }>
        { this.routes }
      </Router>
    );
  }
}
```

**Comment by ocolot** [comment]
Another option is to pass the store directly: `onEnter={(store) => requireAuth(store)}`.
