### ISSUE TITLE
plan to support state object.

### ISSUE THREAD

**Issue by seokgyo** [jlongster/redux-simple-router#21]
history.pushState() takes a state object as first parameter and Link tag takes it as a property. It looks like redux-simple-router do not support this state object yet.
Do you have a plan to support this?

**Comment by jlongster** [comment]
Hadn't thought about it much, but yep, we definitely could add it as a parameter in the `updatePath` parameter, store it in redux and then pass it to `pushState`. Only thing to be careful is to make sure it's a serializable thing, but it probably is.

**Comment by ryanflorence** [comment]
We're going to be adding `push` and `replace` (instead of `pushState` and `replaceState`) to History, the signature will be:

```js
push(path, state)
replace(path, state)
```

Seems like you can just say your API, could get your API ready by adding those two actions as well with the same signature.

**Comment by jlongster** [comment]
@ryanflorence thanks. I'm not sure how I feel about just a `push` and `replace` action; seeing those actions in the wild don't really describe what they do (but as methods on `history` is totally makes sense). Maybe `pushRoute` and `replaceRoute`, or `pushPath` and `replacePath`?

**Comment by jlongster** [comment]
Let's move the discussion for state here: https://github.com/jlongster/redux-simple-router/pull/38
