### ISSUE TITLE
Why store only path and not location with all the props?

### ISSUE THREAD

**Issue by kadmil** [jlongster/redux-simple-router#22]
First of all, thanks for compact and simple thing! Could you tell, what's the motivation beside storing only 'compacted' path string and not the whole location object? It would save users (yes, like me) from manually parsing url string for query params.

**Comment by jlongster** [comment]
You don't need to parse it for query params. Just access it on `this.props` in the routing component. react-router gives everything you need to use it fine without redux. Don't rely on redux to use react-router!

We store the string for 2 reasons: 1. the app state should always be 100% serializable and plain objects, so we don't know if react-router will ever put something non-serializable in there. 2. when changing the path, the user should be able to just supply a string, and if we stored the location we'd have to parse the string into a location object ourselves, and react-router doesn't expose a stand-alone function for doing that.

**Comment by kadmil** [comment]
Wow. Looks like a thing to highlight in docs — didn't knew about it.

**Comment by leoasis** [comment]
@jlongster what would then be a good way to, from an action creator, call `updatePath` and only change the path part while keeping the same search string? In this case you would manipulate the path string? If using the `useQueries` history enhancer it would be great to be able to use and pass the query object along to update the path.
