### ISSUE TITLE
Can't use with reselect

### ISSUE THREAD

**Issue by yanivtal** [jlongster/redux-simple-router#25]
We're trying to clean up our state management with reselect. Selectors act on redux state but some state lives in the URL so we need a way to sync react router state with redux so we can use router params in our selectors.

The problem with this implementation is we can't grab params or queries from state. There's no access to this.props from redux selectors. Any thoughts on how to fix that or will that never be possible with this library?

**Comment by ellbee** [comment]
It is possible to access props from Reselect selectors, `connect` provides props as the second argument to a selector.

https://github.com/rackt/reselect#accessing-react-props-in-selectors

**Comment by yanivtal** [comment]
Gah. I stand corrected. Good implementation choice then. Thanks!
