### ISSUE TITLE
Need more info in state.routing

### ISSUE THREAD

**Issue by dsteinbach** [jlongster/redux-simple-router#26]
Maybe redux-router is a better choice for me because I need a little mas information in state but i'd like to know which route component is currently matched and the params and query params for that route. Redux router also provides me an array of parent routes which is helpful for creating breadcrumb navigations.  Do you know if I can still get this kind of information from react-router directly since it's not currently in state?

**Comment by kadmil** [comment]
I've asked for this, and actually react-router passes all the things into route handler component props. Seemingly, need to update docs on this.

**Comment by kadmil** [comment]
Just use your route handler's props — all is there already.

**Comment by brandondoran** [comment]
Thanks for that tip @kadmil!

To add to that, if you're using the react-redux connect api, you can add a second argument to your mapStateToProps function. It's value will be the props passed into the the component, including router info like routes, params, location, etc.

**Comment by dsteinbach** [comment]
I must have a configuration problem because the only thing I have under `state.routing` is `path`.

**Comment by dsteinbach** [comment]
Argh sorry. Ok I see this all in the route handler props. Thanks!

**Comment by dsteinbach** [comment]
Hmm I might stick with redux-router because having all the routing info in state is just too handy and having to pass around props is going to clutter up my components with dependencies. Although I could create an action that moves this info to state every time the url updates.

**Comment by kadmil** [comment]
@dsteinbach hey, what's the difference between taking routing details from redux-router reducer in `mapStateToProps` or direct component props? And there's an action with update in this project — `UPDATE_PATH `. So, if only reasons are just routing state — it's not show-stopper here.

**Comment by dsteinbach** [comment]
The difference is with redux-router I can grab routing details from any nested component but with redux-simple-router I have to pass props from route handler component down to all the children that need routing details.

**Comment by jlongster** [comment]
@dsteinbach I like to encourage only top-level routing components directly access router props. This aligns with redux's philosophy that generally only top-level components should be "connected". With react-router you can build a deep nested tree but with route components, so the bottom route component still have access to routing props and it's quite deep in the tree.
