### ISSUE TITLE
Immutable state

### ISSUE THREAD

**Issue by unindented** [jlongster/redux-simple-router#29]
All of my state is an `Immutable.js` map. How would I make this work with `redux-simple-router`, given that it's currently checking if `getState().routing` exists?

**Comment by davezuko** [comment]
What about using the third argument `selectRouterState` in `syncReduxAndRouter`, would that solve your issue?

```
syncReduxAndRouter(.., ..., (state) => state.get('routing'));
```

**Comment by unindented** [comment]
Ah, that should totally work. Thanks @davezuko!
