### ISSUE TITLE
replaceState support

### ISSUE THREAD

**Issue by MattKunze** [jlongster/redux-simple-router#32]
Do you have opinions about adding support to replace state in addition to updating it? It seems like there could be parallel `REPLACE_PATH`, `replacePath` exports with internals that mimic the existing functions.

I'm more than happy to come up with a PR, just didn't want to step on any plans that were already in place.

[As mentioned in this comment](https://github.com/jlongster/redux-simple-router/issues/21#issuecomment-156637886) it seems like the history API might be changing as well, though that seems pretty easy to handle.

**Comment by jamischarles** [comment]
Just switched to this from redux-router. Really like the API. Would also love `replaceState`. Could even be a simple 3rd param on the `updatePath` function...

**Comment by MattKunze** [comment]
Yeah, I don't have strong opinions between adding another action or just extending the current one. Not a huge fan of unnamed ordinal binary flags though, I'd prefer something like: `updatePath(path, { noRouterUpdate: false, replaceState: true })`

**Comment by cappslock** [comment]
Came here to say this, more or less.

**Comment by jlongster** [comment]
This is coming :) I wanted to shake out https://github.com/jlongster/redux-simple-router/pull/40 first, because it changes the core code and this still will have to be rebased. Sorry!

**Comment by MattKunze** [comment]
Sweet - I'll probably pull my PR in favor of #38 since it does the same thing and handles state at the same time.

**Comment by jlongster** [comment]
@MattKunze Thanks, sorry for the duplicate work! I'm going to consolidate some of the issues now.
