### ISSUE TITLE
Server-side rendering being discarded because of Redux DevTools

### ISSUE THREAD

**Issue by luandro** [jlongster/redux-simple-router#36]
After better analysing the problem submitted in #31 I realised the issue is with how Redux DevTools is rendered on the server, where the redux-simple-router action's have not yet been dispatched.

```
 (client) c.1.1.1.0.1.$1.0.0">@@router/UPDATE_PATH
 (server) c.1.1.1.0.1.$1.0.0">STARGAZERS_REQUEST</
```

So basically `STARGAZERS_REQUEST` is the first action that is loaded on the server, while redux-simple-router's `@@router/UPDATE_PATH` is the first action loaded on the client. So server-side rendered is discarded on development because of ReduxDevTools, but works fine on production. But than we lose the ability to debug server-side rendering...

**Comment by jlongster** [comment]
The UPDATE_PATH is probably fired because the initial router state is not the same as the first location that history fires. The `history.listen` handler is called once immediately when you register a handler with the current location: https://github.com/jlongster/redux-simple-router/blob/master/src/index.js#L53

But I don't think that should matter. That will happen in the `syncReduxAndRouter` call, which should happen before any components are mounted anyway, so that update will simply just update the store.

I do local server-rendering fine with this project, so I'm not sure where your issue is. Whenever you render the components on the frontend, just make sure that the state is exactly the same as it is on the backend. I don't know what's different without looking at each app state.

**Comment by tomatau** [comment]
I'm having a similar problem.

If navigating to any path other than `/`, the client wishes to fire an UPDATE_PATH and so the invalid checksum pops up for the redux DebugPanel.

To prevent this problem I'm having to do something along these lines in my server side store setup:

```js
  this.store = makeCreateStore(serverMiddleware)(rootReducer, {
    routing: {
      changeId: 1,
      path: this.request.url,
    }
  })
  yield next
```

This allows the server to render the state that my client expects, preventing the invalid checksum from a client calling UPDATH_PATH.

However, it feels wrong :confused:

**Comment by jlongster** [comment]
I'm talking to @tomatau on discord, but I'll respond faster here. It sounds like you're server-rendering the devtools? That doesn't sound like a great idea. You shouldn't need to match the same actions on the server and the client.

**Comment by tomatau** [comment]
I agree that there aren't any benefits gained from server rendering the DebugPanel, however, if we were to only render the DebugPanel on the client, it would still create an invalid checksum.

It's quite simple to share the root level rendering logic between client and server, often that will render the DebugPanel conditionally for the environment, and so there shouldn't be any harm in doing so.

Manually setting initialState with `routing: { changeId: 1, path: this.request.url, }` on the server definitely works anyway, and it's not the biggest pain to do so. Although I have a feeling `IndexRedirect` logic could break this if it skips an actual server redirect.

**Comment by jlongster** [comment]
@tomatau I asked in #redux and others confirmed: you shouldn't be server-rendering the devtools. it's far too common to be dispatching different actions for server and client setup; in my app I definitely dispatch a lot of different actions on the server to set things up. You should design your app to render the devtools only on the client and just dump it into a separate node from your main content.

**Comment by jlongster** [comment]
I don't see how it's possible to create an invalid checksum with your app content. Here it's definitely the devtools contents, which you shouldn't be rendering into the same node as your content if you are wanting to test server-side rendering locally.

**Comment by luandro** [comment]
Important lesson learned about how to use Redux DevTools. It should be mounted on a separate node (on it's own ReactDOM.render method) only on the client. And that solves the problem. Thanks @jlongster and @tomatau.
