### ISSUE TITLE
Back button doesn't work

### ISSUE THREAD

**Issue by ZucchiniZe** [jlongster/redux-simple-router#39]
Going back routes using the browser's back button does not work on the first try, without triggering any actions it takes 3 tries but when I trigger an action it requires a lot more to get back, e.g. 9 clicks of the back button when 2 actions triggered and 14 again when 4 actions triggered.

If it is useful, I am using `react-router`'s `<Link />` component to fashion my links.

**Comment by preflight** [comment]
Confirming that this is the case for me also, and I'm also using `<Link>`. The number of back clicks seems to correspond with the number of history entries being created. I suspected that this was occurring from handling the `UPDATE_PATH` action in my application, but removing this doesn't change the behavior.

**Comment by jlongster** [comment]
Any chance that you all could try this experimental branch? https://github.com/jlongster/redux-simple-router/pull/40

I believe that's going to solve a lot of these issues.

**Comment by jlongster** [comment]
Please try 0.0.9, it should be much more robust. Please re-open this issue if you have problems! I'm 99% sure this should be fixed.

**Comment by LeBlaaanc** [comment]
I'm having this same issue with 0.0.10. Component which initiates the `updatePath` is here:

https://github.com/LeBlaaanc/react-webapp/blob/master/src/components/molecules/SignUpLink/SignUpLink.jsx#L15

It seems transition properly though back doesn't seem to work.

**Comment by jlongster** [comment]
Check out #45, we're debugging those kind of issues there now.

**Comment by LeBlaaanc** [comment]
@jlongster I think maybe I am not binding the `updatePath` action to the store properly. I'm going to simplify this and use `dispath(updatePath(...))` and see if this helps. Might be my fault.

**Comment by dimroc** [comment]
Hi all,
I'm also having an issue with the back button. Essentially, the back button doesn't pop the state object. This results in the browser going back a page but not updating the state object and therefore the contents of the page.

Perhaps I'm doing something wrong. Any help would be appreciated!

**Comment by shea256** [comment]
@dimroc @jlongster I'm having the same issue and I have npm version `2.1.0`.

**Comment by jlongster** [comment]
Please open a new issue with your specific STR.

**Comment by kevnk** [comment]
Hi All, did anyone find (and remember) a solution here? @jlongster what's "STR"?
