### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by jmarquis** [jlongster/redux-simple-router#44]
I saw the v0.0.10 update today but can't find any record of changes since the last version. Is there intentionally no changelog at this point? With the increasing number of projects that are relying on this, I'd say it's worth bumping to v0.1 or v1 and recording changes between releases ASAP. Hard to decide how to maintain this as a dependency otherwise.

Thanks for the great work, @jlongster!

**Comment by DLMR** [comment]
For now you can look at this to get a understanding on what has changed https://github.com/jlongster/redux-simple-router/compare/0.0.8...0.0.10.

**Comment by jlongster** [comment]
Good point. Generally it was a bugfix release, but I should make a changelog. I will do that for the next version, which will be especially important because I thin we are going to change some of the methods (see #38)

**Comment by jmarquis** [comment]
Great! Thanks for the update. Feel free to close this if you won't be working against it.

**Comment by jlongster** [comment]
Ok. I'll start a changelog and maybe even try to go back into past versions. We're going to push a new release after https://github.com/jlongster/redux-simple-router/pull/38 gets merged so I'll start it then.
