### ISSUE TITLE
Uncaught TypeError: listener is not a function

### ISSUE THREAD

**Issue by LeBlaaanc** [jlongster/redux-simple-router#46]
I've gone through and refactored my `createStore` code a few times and looked at some of the related issues and sample code and still can't seem to figure out why I keep getting: 

```Uncaught TypeError: listener is not a function```

Here's my complete code and where the store is sync'd:
https://github.com/LeBlaaanc/react-webapp/blob/master/client.jsx#L14

I swear this was working and then it blew up. Any thoughts or help is much appreciated.

**Comment by jlongster** [comment]
Hm where does the error come from? Have you looked there? Does it come from within react-router?

If you look at this code, we don't have a `listener` variable anywhere nor do we try to call it.

**Comment by LeBlaaanc** [comment]
It comes from `createStore.js` line 132 of redux. Maybe I have a subscriber that's screwing it up.

**Comment by jlongster** [comment]
Hm, or maybe a middleware? We do pass a function in as a listener. I don't know if you can, but would be helpful to add some logging to the `subscribe` code in redux to see what comes through.

**Comment by LeBlaaanc** [comment]
Yea was my subscriber that was blowing it up. Not sure exactly what part of it but I'll figure that out.

That being said I'm now having trouble with the back button, no errors are thrown, I was thinking the listener error was preventing the back from working. I can go in a reopen that other issue related to the back button that was suggested to be fixed 0.0.9.

**Comment by LeBlaaanc** [comment]
I'll elaborate in #39.

**Comment by jlongster** [comment]
Closing this as there is no action. It sounds like it's mostly issues with your code. Thanks!
