### ISSUE TITLE
FSA

### ISSUE THREAD

**Issue by mlucool** [jlongster/redux-simple-router#53]
Hi,

What are your thoughts on moving this to support Flux-Standard-Actions? https://github.com/acdlite/flux-standard-action

Thanks,
Marc

**Comment by jlongster** [comment]
I'd be open to it if it helps other people. Does it affect people using it if we don't use it?

**Comment by dferber90** [comment]
I am using a middleware which makes sure all actions passed through are FSA compliant. I currently added an exception for redux-simple-router. Would welcome having FSA compliant actions :+1:

Don't think it would affect people using it, but the advantages of FSA (listed in the repo) apply here as well I'd say.

**Comment by tomatau** [comment]
:+1:

**Comment by neverfox** [comment]
:+1:

**Comment by jlongster** [comment]
Done in #63

**Comment by mlucool** [comment]
Thanks!
