### ISSUE TITLE
Invariant violation with syncReduxAndRouter + inline click handler

### ISSUE THREAD

**Issue by mking** [jlongster/redux-simple-router#54]
**EDIT** Closing because I don't think this is specific to `redux-simple-router`

With `syncReduxAndRouter`, I am seeing the following error in the console:
```
Uncaught Error: Invariant Violation: findComponentRoot(..., .0.2.1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
```

Without `syncReduxAndRouter`, the issue does not occur.

Here is a [reproducible test case](https://github.com/mking/sync-dispatch).
* To reproduce the error, open the console and select a user.

I did a little digging and I believe I have some idea of why we are getting an invariant violation.

1. When the user selects an option, the `selectUser` action is dispatched.
2. In `redux-simple-router`, the `subscribe` callback is invoked synchronously. Because the change ids do not match, pushState occurs.
3. In `react-router` ([`<Router/>`](https://github.com/rackt/react-router/blob/master/modules/Router.js#L48)), the history listener is invoked synchronously. This results in a `setState`.
4. In `react-redux` (`@connect`), the `subscribe` callback is invoked synchronously. This results in a second `setState` within the same cycle.
5. For reasons unknown to me (this might be due to React internals), two `setState` calls within the same cycle cause React to incorrectly search for the above data-reactid (`.0.2.1`), resulting in an invariant violation because the element cannot be found. (This data-reactid corresponds to an element that should be omitted from the render tree given the current props and state.)

I was thinking the solution, if possible, would be to eliminate the double setState. I see the React developers [have looked into this a bit in a different context](https://github.com/facebook/react/issues/122), and it does not seem to be supported.

**Comment by patrickheeney** [comment]
Did you ever figure this out? I think I am experiencing something similar, if not the same in my app. Without `syncReduxAndRouter` the issue does not occur for me either. In my case the invariant error is because React is looking or a button that should no longer exist giving the current props.

**Comment by websilone** [comment]
Same here !
I was facing the same issue. After reading your comments, I tried to remove syncReduxAndRouter and the error was gone !
I did not investigated more on this yet but not sure @mking is totally right when he says that it is not due to redux-simple-router...

**Comment by patrickheeney** [comment]
I upgraded to react-router v2 (still leaving off `syncReduxAndRouter`) and it continues to work. I am hoping that updating `redux-simple-router` when it is v2 compatible will resolve the error. I also need `Immutable` support for me to be able to go back, but for now I will heave to leave it behind.

**Comment by websilone** [comment]
@patrickheeney I also upgraded to react-router v2 without syncReduxAndRouter and it's working fine.
But I ran into the error one more time and found a way to fix it. I guess I was dispatching a redux action and then changing the route. This is where React was lost.
I changed the way to handle this with a better sequencing and grouping my dispatches and it worked again.

**Comment by patrickheeney** [comment]
> I changed the way to handle this with a better sequencing and grouping my dispatches and it worked again.

In my case I was dispatching after a promise so it "should" have worked, something like: `return dispatch => dispatch({ type: TEST }).then(dispatch(pushState('/test'))`. What did you change?

**Comment by websilone** [comment]
I had something like this
`<Link onClick={ someActionFromTheProps } to="/a/new/route" />`

Knowing that, `someActionFromThePros` was a Redux action doing a `dispatch` and that the component called when the route was changed was doing something like : 

 ```
componentWillReceiveProps (nextProps) {
  if(nextProps.someId !== this.props.someId) {
    this.props.anoterReduxAction();
  }
}
```

where `anotherReduxAction`was also doing a `dispatch`.

So what I changed finally is removing the `onClick` on the `Link`and doing this dispatch within the `anotherReduxAction`which looks like something like this now : 

```
const anotherReduxAction = () => {
  return dispatch => {
    dispatch(someActionFromTheProps); // which was done in the onClick initially
    dispatch(theOriginalAction);
  }
}
```

I hope it's clear enough^^

**Comment by jlongster** [comment]
Please open a new issue will clear steps to reproduce if you want to discuss it more. Thanks! Also, on master is a totally refactored API that hopefully solves more problems. You can try it out with `npm install redux-simple-router@next`
