### ISSUE TITLE
Weird initial state when using hash history

### ISSUE THREAD

**Issue by heydemo** [jlongster/redux-simple-router#58]
Accessing my app at http://localhost/react-bliss/public/index.html
 
The initial state for routing is set to /react-bliss/public/index.html

The history listener then updates the path to '/'

However with [Redux Persist](https://github.com/rt2zz/redux-persist/issues/2) the store is updated before the update path action sets the correct path of '/'

This triggers redux-simple-router's store subscribe function and pushs the initial state to the browser - so I get a browser URL of http://localhost/react-bliss/public/index.html#/react-bliss/public/index.html?_k=djhrwj

This seems a symptom of the initial state redux-simple-router is using not being the 'real' initial state with hash history.

Potential solutions:

1.  Detect hash history is being used (if possible) or set a config option to specify hash history - and then in locationToString return only the hash
2. Allow locationToString to be over-ridden by a user supplied function in a config object

Use case:

Using redux-simple-router with redux-persist and accessing at a url with a non-hash path
i.e. localhost/myapp/index.html instead of myapp.localhost

In my case I need to be able to access at the first url because I am using this with cordova and cannot rewrite the URL

**Comment by jlongster** [comment]
We've recently changed a lot of this code. Can you try master? This might be fixed.

**Comment by heydemo** [comment]
@jlongster Yes, working flawlessly now.  Thanks for your work
