### ISSUE TITLE
0.0.10 breaks devtools

### ISSUE THREAD

**Issue by idan** [jlongster/redux-simple-router#61]
I originally filed this issue on freeqaz/redux-simple-router-example#1. I am able to reproduce the behavior elsewhere by switching between `0.0.8` and `0.0.10`, so maybe this is a more appropriate place to file the issue?

Gif for your viewing pleasure:

![](http://f.cl.ly/items/330P3f2M3p1p1M013m1l/Screen%20Recording%202015-11-30%20at%2014%3A09.gif)

The only change I see to the state as reported by devtools is the addition of `changeId`.

**Comment by jlongster** [comment]
The gif (which is awesome, really helps thanks) is showing 0.0.8. Are you sure that it worked in 0.0.8 and broke in 0.0.10? It's confusing that you aren't showing it breaking the latest version.

**Comment by idan** [comment]
Hmm, weird. I definitely recorded it with the latest version, which included `changeId` in the state. Maybe I didn't properly blow away my `node_modules`? Will retry.

**Comment by idan** [comment]
From the other issue, here's screenshots of the state for each version:

Here's devtools' picture of the state changes in 0.0.8:

![cursor_and_redux-simple-router_example](https://cloud.githubusercontent.com/assets/22723/11471258/c8dfb160-976c-11e5-9b43-012e11dd49c9.jpg)

And here's the same thing for 0.0.10:

![redux-simple-router_example_and_package_json_-__users_igazit_dropbox_heroku_redux-simple-router-example_-_atom_and_configurestore_dev_js_-__users_igazit_dropbox_heroku_herokudata_-_atom](https://cloud.githubusercontent.com/assets/22723/11471239/a2bdca9e-976c-11e5-98e5-8eacb5982bf8.jpg)

**Comment by jlongster** [comment]
Oh, you are right. I think I was looking at the action but thinking that was state. In previous versions we actually stored the `avoidRouterUpdate` flag in the state.

I'll take a look soon.

**Comment by rdelatorre** [comment]
Glad to see that someone else reported this! I was about to report it as well, except that I don't know how to make cool animated GIFs, so I maybe wouldn't have been as helpful.

(P.S. What are you using to make your animated GIFs?)

**Comment by idan** [comment]
@rdelatorre I use [cloudapp](https://www.getcloudapp.com/), but there are a number off free options out there along the power/simplicity curve:

* [Licecap](http://www.cockos.com/licecap/)
* [Recordit](http://recordit.co/)
* [quicktime->ffmpeg flavor 1](https://gist.github.com/dergachev/4627207)
* [quicktime->ffmpeg flavor 2}(http://spin.atomicobject.com/2015/07/08/simple-gif-screencast-workflow-mac/)

**Comment by fkrauthan** [comment]
I have the same issue with my project. I started right away with the latest version but the ReduxDevTool events have no influence on my application state.

**Comment by fkrauthan** [comment]
The problem is the history listen dispatching of event. You set avoidRouterUpdate to true which results in not counting up the change id. So lastChangeId is always gonna be equal to changeId so you never update the route when the store changes.

**Comment by jlongster** [comment]
@kjbekkelund Have you tried it with devtools yet? I will very soon but work has just been crazy. I'll add the devtools to the `basic` example which will help have a quick simple project to diagnose issues.

**Comment by geowarin** [comment]
As @fkrauthan says, incrementing the changeId systematically does fix the problem.
However, it also breaks a bunch of tests.

My guess is https://github.com/jlongster/redux-simple-router/blob/master/src/index.js#L95 will stop redux from replaying the changes when going back in time.

**Comment by fkrauthan** [comment]
Don't we just need a flag outside of the two listeners that gets used to prevent a router change triggering a endless loop instead of relaying on that id?

**Comment by kjbekkelund** [comment]
@jlongster Haven't had time to play with devtools yet. Will try to get some time to do it soon.

**Comment by idan** [comment]
:heart: :sparkles: Thank you!
