### ISSUE TITLE
Using  basename for history causes infinite loop

### ISSUE THREAD

**Issue by kromit** [jlongster/redux-simple-router#64]
I want to run my app in a context so i need a history basename:

    import {createHistory,useBasename} from 'history';
    const history = useBasename(createHistory)({
        basename: '/mybase'
    });

I also use an `onEnter` in the route which loads current session and calls `dispatch`. The `dispatch` runs into the `syncReduxAndRouter` and call `pushState` causing the loop. This happens because redux-simple-router uses `window.location` to check the changes and is not is not aware of the `basename` used in the history so it always calls `pushState`

**Comment by kromit** [comment]
0.0.10 fixed this

**Comment by neverfox** [comment]
@kromit I'm getting the infinite loop with 1.0.1.

**Comment by neverfox** [comment]
Got around it by bumping history to 1.17.0, but now I've posted #146 as an ongoing issue.
