### ISSUE TITLE
redux-simple-router@0.0.10 doesn't work with redux-devtools

### ISSUE THREAD

**Issue by datpham23** [jlongster/redux-simple-router#66]
I'm using  redux-devtools@2.1.5 with redux-simple-router@0.0.10 and the action toggling feature doesn't work. The route does not change when I toggle the action in the DebugPanel component. However it works when I switch redux-simple-router to 0.0.8.

**Comment by fkrauthan** [comment]
This is a duplicate of #61

**Comment by jlongster** [comment]
Closing as dupe, thanks.
