### ISSUE TITLE
history.pushState vs updatePath

### ISSUE THREAD

**Issue by gschwa** [jlongster/redux-simple-router#67]
Is it safe to assume that we should only be using `updatePath(...)` vs `history.pushState(...)`?

**Comment by download13** [comment]
Assuming by `history` you mean the object you got from `createBrowserHistory` and not `window.history`, then can do either and it would work the same.

Personally, I like to do everything by dispatching actions. Having one way of doing things just feels simpler, plus you don't have to be carting the `history` object around to every bit of code that might need it. It's basically a piece of application state, so exposing it to the rest of your code would kind of defeat the point of using redux.

That said, if you have synced the store and history object already any direct calls on history should trigger the corresponding action to be dispatched on the store.

**Comment by jlongster** [comment]
As mentioned above, either work fine actually. The point of this library a bidirectional sync: update one, and the other will update as well. You can use `history.pushState` just fine if you want, but most of the time you will probably be using `<Link>` tags and the `pushPath` action.
