### ISSUE TITLE
Add react-router data into action and reducer

### ISSUE THREAD

**Issue by vladimirbuskin** [jlongster/redux-simple-router#68]
Add react router data into action and reducer

```javascript
components: Array[],
location: Object,
params: Object,
routes: Array[]
```

I make a commit, just to show my Idea

https://github.com/vladimirbuskin/redux-simple-router/commit/0c4240ba63efe1454fdb0b762b109a710c4e03f5

Can we add something like that into simple router, because i think it is significant.
Data is great in actions to use in middlewares, and usefull in state as well. For example will help to use router in 
react-redux-universal-hot-example

what do you think?

**Comment by jlongster** [comment]
Definitely not, sorry. If you want that, use redux-router. It complicates things significantly, and you should only be putting serializable dumb state in your app state. The idea of the project is that you should use react-router directly; you should use redux-router if you want a separate interface.

**Comment by jlongster** [comment]
We're porting react-redux-universal-hot-example, and there's been little problems using react-router directly FWIW.

**Comment by vladimirbuskin** [comment]
ok, yes, just realized that could be or should be done withing middleware 
like
transitionMiddleware.js in react-redux-universal-hot-example
