### ISSUE TITLE
When will the next release be?

### ISSUE THREAD

**Issue by download13** [jlongster/redux-simple-router#75]
I noticed that the master branch has been updated to export `pushPath` and `replacePath` instead of `updatePath`. The version number is the same as the current release though, and I was wonder how long it will be before the next version-increment/release.

Being able to replace the current path is a blocking feature for me.

PS: Great library! Even without replace I like it a lot better than react-router.

**Comment by jlongster** [comment]
Thanks! It will be released today. The changes have sat on master for a while and there were a few issues to figure out but I think we are now good to go. Just a few small things to do before I release it.
