### ISSUE TITLE
Required propTypes warning

### ISSUE THREAD

**Issue by yangsibai** [jlongster/redux-simple-router#87]
After using `redux-simple-router`, I get many warnings like "Warning: Failed propType: Required prop `foo` was not specified in `FooComp`. Check the render method of `RoutingContext`."

But when I checked the `prop` in the `FooComp`, it's already there.

It this a bug?

**Comment by kjbekkelund** [comment]
Do you have a small example that shows this? I'm using the lib on my app and have no problems with PropTypes. Btw, `RoutingContext` is a react-router component, is has nothing to do with redux-simple-router.

**Comment by yangsibai** [comment]
I have routes like this:

```
<Provider store={store}>
	<Route path="/" component={App}>
		<Route path="foo" component={FooComp}>
			<Route path="bar" component={BarComp} />
		</Route>
	</Route>
</Provider>
```
and components:

**FooComp:**

```
var FooComp = React.createClass({
	propTypes: {
		bar: React.PropTypes.string.isRequired
	},
	render: function () {
		return (
			<div>{this.renderChildren()}</div>
		)
	},
	renderChildren: function () {
		return React.Children.map(this.props.children, function (child) {
			return React.cloneElement(child, {
				bar: this.props.bar
			})
		}.bind(this));
	}
});
```

**BarComp:**

```
var BarComp = React.createClass({
	propTypes: {
		bar: React.PropTypes.string.isRequired
	},
	render: function () {
		return (
			<div>{this.props.bar}</div>
		)
	}
});
```

I didn't write these codes into a sample project, I havn't verify if these will get the same warning. I will make a project if need.

**Comment by kjbekkelund** [comment]
This doesn't seem to have anything to do with redux-simple-router

**Comment by yangsibai** [comment]
@kjbekkelund Thank you for your agile reply . Maybe I should make an issue in `react-router`.
