### ISSUE TITLE
Support for relative path in updatePath

### ISSUE THREAD

**Issue by yangsibai** [jlongster/redux-simple-router#88]
Do you have a plan for supporting relative path in `updatePath`?

When I use relative path in `updatePath`, I can see the URL change but get a warning: `Warning: Location "foo" did not match any routes`

**Comment by kjbekkelund** [comment]
We don't do anything to the path before [calling `history.pushState`](https://github.com/jlongster/redux-simple-router/blob/0.0.10/src/index.js#L70), so we only support its api.

**Comment by atran** [comment]
I have no idea how to do base relative URLs.
