### ISSUE TITLE
UpdatePath after API call

### ISSUE THREAD

**Issue by banderson5144** [jlongster/redux-simple-router#99]
What is the best way to update the path after making an API call? Right now I am making my API call but it is getting to the component before the all the data has loaded.

This is how I am doing it now:

```javascript
this.props.dispatch(getSpecAcct(e));
this.props.dispatch(updatePath('/comppage'));
```

**Comment by kjbekkelund** [comment]
If you're using [Redux thunk](https://github.com/gaearon/redux-thunk), you could do something like this:

```
store.dispatch(
  this.props.dispatch(getSpecAcct(e));
).then(() => {
  this.props.dispatch(updatePath('/comppage'));
});
```

(There's lots of examples in their docs)

If you're not using Redux thunk you could instead base it on the data in the store, or something like that.

**Comment by banderson5144** [comment]
When I do that, it says '''then''' is not a function. And yes I am using thunk

**Comment by kjbekkelund** [comment]
Follow the examples in the Redux thunk lib, especially the section on "Composition". The important thing for this to work it that you return a promise in the thunk, see the `makeASandwichWithSecretSauce` function for an example.

What you also can do is move the dispatch of `getSpecAcct` into the component rendered for `'/comppage'`. This is what I do (i.e. no requests and url dispatches at the same time, I first change url then download what's needed in the new component).

If you can't get it working, please create a StackOverflow question instead.
